GET http://localhost:3000/api/images

###

GET http://localhost:3000/api/images/2

###

POST http://localhost:3000/api/images
Content-Type: application/json

{
    "name": "image.jpg",
    "path": "/resources/image.jpg",
    "type": "jpeg"
}

###

PUT http://localhost:3000/api/images/3
Content-Type: application/json

{
    "name": "new_image.jpg",
    "path": "/uploads/new_image.jpg",
    "type": "png"
}

###

DELETE http://localhost:3000/api/images/3
